### ISSUE TITLE
Logo color

### ISSUE THREAD

**Issue by klequis** [trivalleycoders-org/trivalleycoders#18]
The logo is currently blue / white
Sites colors are black / green
Blue clashes.
Considering green or grayscale logo

**Comment by klequis** [comment]
We have a green and blue version. Will decide which to use depending on final color scheme.

**Comment by proteasome** [comment]
i was thinking we could might color code depending on language/stack.  i'm using a bootleg version on my personal site, which is Python/Julia notioned.
