### ISSUE TITLE
Connect TechLogos to data in mongoDB

### ISSUE THREAD

**Issue by klequis** [trivalleycoders-org/trivalleycoders#23]
1. Create /server/scripts/init.mongo.techlogos and populate with data (same as is in the file /server/seed-data/technologies.js WITHOUT the 'id' as mongo will autocreate _id
2. Load data to mongo
3. Create selector in /client/store/selectors.js (pattern after getEvents)
4. Add to reducers 'byId' and 'ids'
5. Add connect, mapStateToProps, etc to the TechLogo component (pattern after Events)
> may the force be with you

**Comment by chad187** [comment]
ready for review!
