### ISSUE TITLE
Put meta data for Nav buttons in mongo and render them from that dat

### ISSUE THREAD

**Issue by klequis** [trivalleycoders-org/trivalleycoders#24]
1. design data shape
1. put seed data in mongo
2. build api request
3. modify UI to consume data from api

**Comment by klequis** [comment]
Initial thoughts on data shape
- _id will come from mongo auto id
- buttonName: string (not sure we need it)
- buttonIcon: url or fontawesome resource
- buttonText: string
- order: number (0 based, determines order of buttons in nav bar)

**Comment by chad187** [comment]
I don't see any Nav button components.  Is this referring to ButtonTVC?
