### ISSUE TITLE
Footer: design and implement footer

### ISSUE THREAD

**Issue by klequis** [trivalleycoders-org/trivalleycoders#55]
Working on this issue

1. comment here the content you think should go in the footer to get feedback. It can be as fancy or as plain as you want.
2. Get feedback and agreement
3. Implement it

**Comment by klequis** [comment]
I'm thinking
- copyright: © 2017 Tri-Valley Coders. All rights reserved
- Join on Meetup
- Facebook

**Comment by LauraSilvey** [comment]
Agree with above suggestions + link to github

**Comment by LauraSilvey** [comment]
Changes have been approved and merged.
