### ISSUE TITLE
Tab creation for Event click

### ISSUE THREAD

**Issue by proteasome** [trivalleycoders-org/trivalleycoders#56]
When an link under Events is clicked on a new tab is created instead of staying on the same tab.  seems unnecessary tab clutter and possibly resource expensive.  

for example:
http://trivalleycoders.herokuapp.com
Let's Code! - Study/help SessionSpecialty's Cafe & Bakery
5331 Hopyard Rd, PleasantonThu Jun 29, 9:00 AM

testing other sites indicate that my local settings are not the likely cause

using macOS Sierra 10.12.4,  behavior is same on all three browsers
Safari 10.1 (12603.1.30.0.34)
FF 54.0 (64-bit)
Chrome 59.0.3071.109 (64-bit)

[[for users who really want to do this browsers often do have ways for users to intentionally do so, e.g. cntl-click (open and move to new tab). and cmd-click open and do not move to new tab)]]

**Comment by LauraSilvey** [comment]
issue completed, approved and merged
