### ISSUE TITLE
Design API routes

### ISSUE THREAD

**Issue by klequis** [trivalleycoders-org/trivalleycoders#8]

**Comment by chad187** [comment]
How so??

**Comment by klequis** [comment]
So far we are accomplishing this one at a time. Not a tidy process but has worked for learning.
We will need to add, add, update and delete for a couple such as members but maybe not till v0.2

**Comment by klequis** [comment]
I think the next step is add project.

Here is a cheatsheet

**Comment by klequis** [comment]
Routes are being designed in issue [#40](https://github.com/trivalleycoders-org/trivalleycoders/issues/40).
